language: python
python:
  - "3.8"
install:
  - "pip install pipenv"
  - "pipenv sync"
before_script:
  - pip install --dev
  - cd -
script:
  - py.test template/tests.py --cov=template
after_success:
  - coveralls
